cyan/new:
  active: true
  history:
    - version: 12
      time: 2025-09-20T03:38:04.250314Z
      answers:
        cyan/new/username:
          type: String
          value: atomi
        cyan/new/description:
          type: String
          value: AtomiCloud's Cyanprint Template Template
        cyan/new/more-processors/0:
          type: String
          value: yes
        cyan/new/email:
          type: String
          value: admin@atomi.cloud
        cyan/new/more-processors/1:
          type: String
          value: no
        cyan/new/tag/1:
          type: String
          value: atomi
        cyan/new/name:
          type: String
          value: atomi-cyan
        cyan/new/tag/0:
          type: String
          value: template
        cyan/new/more-tags/2:
          type: String
          value: no
        cyan/new/processor/0:
          type: String
          value: cyan/default
        cyan/new/create:
          type: String
          value: Template
        cyan/new/more-tags/0:
          type: String
          value: yes
        cyan/new/more-tags/1:
          type: String
          value: yes
        cyan/new/project:
          type: String
          value: https://github.com/AtomiCloud/ketone.atomi-cyan
        cyan/new/source:
          type: String
          value: https://github.com/AtomiCloud/ketone.atomi-cyan.git
        cyan/new/more-plugins/0:
          type: String
          value: no
        cyan/new/language:
          type: String
          value: Typescript
      deterministic_states: {}
atomi/workspace:
  active: true
  history:
    - version: 20
      time: 2025-09-20T03:48:46.785460Z
      answers:
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/enable-helm:
          type: Bool
          value: false
        atomi/workspace/platform:
          type: String
          value: ketone
        atomi/workspace/service:
          type: String
          value: atomi-cyan
        atomi/workspace/enable-docker:
          type: Bool
          value: true
        atomi/workspace/runtime:
          type: String
          value: Bun
      deterministic_states: {}
    - version: 20
      time: 2025-09-20T03:53:51.948187Z
      answers:
        atomi/workspace/runtime:
          type: String
          value: Bun
        atomi/workspace/enable-helm:
          type: Bool
          value: false
        atomi/workspace/service:
          type: String
          value: atomi-cyan
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/platform:
          type: String
          value: ketone
        atomi/workspace/enable-docker:
          type: Bool
          value: false
      deterministic_states: {}
atomi/nix-init:
  active: true
  history:
    - version: 13
      time: 2025-09-20T03:46:43.070686Z
      answers:
        init-type:
          type: String
          value: CyanPrint Bun
      deterministic_states: {}
