atomi/workspace:
  active: true
  history:
    - version: 20
      time: 2025-09-20T04:18:17.086559Z
      answers:
        atomi/workspace/runtime:
          type: String
          value: Bun
        atomi/workspace/platform:
          type: String
          value: constxxplatformxx
        atomi/workspace/service:
          type: String
          value: constxxservicexx
        atomi/workspace/enable-docker:
          type: Bool
          value: true
        atomi/workspace/enable-helm:
          type: Bool
          value: false
        atomi/workspace/enable-secret:
          type: Bool
          value: false
      deterministic_states: {}
cyan/new:
  active: true
  history:
    - version: 12
      time: 2025-09-20T04:16:50.929573Z
      answers:
        cyan/new/more-tags/1:
          type: String
          value: no
        cyan/new/more-processors/0:
          type: String
          value: yes
        cyan/new/tag/0:
          type: String
          value: atomi
        cyan/new/more-tags/0:
          type: String
          value: yes
        cyan/new/project:
          type: String
          value: https://github.com/AtomiCloud/constxxplatformxx.constxxservicexx
        cyan/new/language:
          type: String
          value: Typescript
        cyan/new/description:
          type: String
          value: constxxdescxx
        cyan/new/more-processors/1:
          type: String
          value: no
        cyan/new/processor/0:
          type: String
          value: cyan/default
        cyan/new/username:
          type: String
          value: atomi
        cyan/new/name:
          type: String
          value: constxxtemplatenamexx
        cyan/new/email:
          type: String
          value: admin@atomi.cloud
        cyan/new/create:
          type: String
          value: Template
        cyan/new/more-plugins/0:
          type: String
          value: no
        cyan/new/source:
          type: String
          value: https://github.com/AtomiCloud/constxxplatformxx.constxxservicexx.git
      deterministic_states: {}
atomi/nix-init:
  active: true
  history:
    - version: 13
      time: 2025-09-20T04:17:58.544143Z
      answers:
        init-type:
          type: String
          value: CyanPrint Bun
      deterministic_states: {}
